version: '3.8'
services:
  print-server:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*